#!/usr/bin/env ruby

require 'yaml'
require 'todo-txt'
require 'pry'

require_relative 'config.rb'
require_relative 'lib/string.rb'

config_file = ENV['HOME'] + "/.askew/askew.config"

config = Config.new "Foobar"

puts "Color should be red".red
puts "Non bold" + " text should be bold".bold + " Non Bold again."

begin
  config = YAML.load(File.open(config_file))

  if config.include? 'user'
    name = config['user']['name'] if config['user'].include? 'name'
  end

  if config.include? 'data'
    base_dir = config['data']['todo_base_dir'] if config['data'].include? 'todo_base_dir'
    if base_dir 
      todo_file2 = base_dir + config['data']['todo_file'] if config['data'].include? 'todo_file'
    end
  end

rescue ArgumentError => e
  puts "Could not parse YAML: #{e.message}"
rescue Exception => e
  puts "Unable to load config from: #{config_file}" 
  puts "Exception : #{e.message}"
end


begin
  puts "No definition found for ASKEW_TODO_LOCATION" if !ENV["ASKEW_TODO_LOCATION"]
  list = Todo::List.new ENV["ASKEW_TODO_LOCATION"]
  #puts list.by_priority "A"
  #binding.pry
  #puts list.sort_by { |task| task.priority }
  puts list.sort_by {|item| [item.priority ? 0 : 1, item.priority || 0]} # list by priorty with nulls at the end
rescue
  puts "Unable to load your todo list."
end
#list = Todo::List.new "/home/dhaskew/Dropbox/todo/todo.txt"
#list = Todo::List.new "/Users/daskew/Dropbox/todo/todo.txt"

