#!/usr/bin/env ruby

require 'todo-txt'
require 'pry'

#binding.pry

begin
  puts "No definition found for ASKEW_TODO_LOCATION" if !ENV["ASKEW_TODO_LOCATION"]
  list = Todo::List.new ENV["ASKEW_TODO_LOCATION"]
  #puts list.by_priority "A"
  #binding.pry
  #puts list.sort_by { |task| task.priority }
  puts list.sort_by {|item| [item.priority ? 0 : 1, item.priority || 0]} # list by priorty with nulls at the end
rescue
  puts "Unable to load your todo list."
end
#list = Todo::List.new "/home/dhaskew/Dropbox/todo/todo.txt"
#list = Todo::List.new "/Users/daskew/Dropbox/todo/todo.txt"

